<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('items')->insert([
            // Pain Relief & Fever (Category 1)
            [
                'name' => 'Paracetamol 500mg',
                'gst_percent' => 12,
                'pack_id' => 1,
                'number_of_units' => 10,
                'unit_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 1,
                'rack' => 'A1',
                'hsn_code' => '300490',
                'sch_type' => 'H',
                'manufacturer_id' => 1,
                'molecule' => 'Paracetamol',
                'barcode' => 'PARA500001',
                'min_threshold' => 5,
                'max_threshold' => 50,
                'need_prescription' => 0,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 1,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 10,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dolo 650',
                'gst_percent' => 12,
                'pack_id' => 1,
                'number_of_units' => 15,
                'unit_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 1,
                'rack' => 'A2',
                'hsn_code' => '300490',
                'sch_type' => 'H',
                'manufacturer_id' => 1,
                'molecule' => 'Paracetamol',
                'barcode' => 'DOLO650001',
                'min_threshold' => 5,
                'max_threshold' => 60,
                'need_prescription' => 0,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 1,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 12,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ibuprofen 400mg',
                'gst_percent' => 12,
                'pack_id' => 1,
                'number_of_units' => 15,
                'unit_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 1,
                'rack' => 'A3',
                'hsn_code' => '300490',
                'sch_type' => 'H',
                'manufacturer_id' => 2,
                'molecule' => 'Ibuprofen',
                'barcode' => 'IBU400001',
                'min_threshold' => 5,
                'max_threshold' => 45,
                'need_prescription' => 0,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 1,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 12,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nimesulide 100mg',
                'gst_percent' => 12,
                'pack_id' => 1,
                'number_of_units' => 10,
                'unit_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 1,
                'rack' => 'A4',
                'hsn_code' => '300490',
                'sch_type' => 'H',
                'manufacturer_id' => 3,
                'molecule' => 'Nimesulide',
                'barcode' => 'NIME10001',
                'min_threshold' => 5,
                'max_threshold' => 40,
                'need_prescription' => 1,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 1,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 10,
                'notes' => 'NSAID - Prescription required',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Diclofenac 50mg',
                'gst_percent' => 12,
                'pack_id' => 1,
                'number_of_units' => 10,
                'unit_id' => 1,
                'category_id' => 1,
                'sub_category_id' => 1,
                'rack' => 'A5',
                'hsn_code' => '300490',
                'sch_type' => 'H',
                'manufacturer_id' => 2,
                'molecule' => 'Diclofenac',
                'barcode' => 'DICL50001',
                'min_threshold' => 5,
                'max_threshold' => 50,
                'need_prescription' => 1,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 1,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 10,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Antibiotics (Category 2)
            [
                'name' => 'Amoxicillin 500mg',
                'gst_percent' => 12,
                'pack_id' => 1,
                'number_of_units' => 10,
                'unit_id' => 1,
                'category_id' => 2,
                'sub_category_id' => 2,
                'rack' => 'B1',
                'hsn_code' => '300410',
                'sch_type' => 'H',
                'manufacturer_id' => 4,
                'molecule' => 'Amoxicillin',
                'barcode' => 'AMOX500001',
                'min_threshold' => 5,
                'max_threshold' => 40,
                'need_prescription' => 1,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 0,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 18,
                'max_discount' => 10,
                'notes' => 'Requires prescription',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Azithromycin 500mg',
                'gst_percent' => 12,
                'pack_id' => 1,
                'number_of_units' => 5,
                'unit_id' => 1,
                'category_id' => 2,
                'sub_category_id' => 2,
                'rack' => 'B2',
                'hsn_code' => '300490',
                'sch_type' => 'H',
                'manufacturer_id' => 5,
                'molecule' => 'Azithromycin',
                'barcode' => 'AZIT50001',
                'min_threshold' => 3,
                'max_threshold' => 30,
                'need_prescription' => 1,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 0,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 8,
                'notes' => 'Azithromycin tablets',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ciprofloxacin 500mg',
                'gst_percent' => 12,
                'pack_id' => 1,
                'number_of_units' => 10,
                'unit_id' => 1,
                'category_id' => 2,
                'sub_category_id' => 2,
                'rack' => 'B3',
                'hsn_code' => '300420',
                'sch_type' => 'H',
                'manufacturer_id' => 4,
                'molecule' => 'Ciprofloxacin',
                'barcode' => 'CIPR50001',
                'min_threshold' => 5,
                'max_threshold' => 35,
                'need_prescription' => 1,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 0,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 10,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Antihistamines (Category 3)
            [
                'name' => 'Cetirizine 10mg',
                'gst_percent' => 12,
                'pack_id' => 2,
                'number_of_units' => 10,
                'unit_id' => 2,
                'category_id' => 3,
                'sub_category_id' => 3,
                'rack' => 'C1',
                'hsn_code' => '300490',
                'sch_type' => 'G',
                'manufacturer_id' => 18,
                'molecule' => 'Cetirizine',
                'barcode' => 'CETI10001',
                'min_threshold' => 10,
                'max_threshold' => 100,
                'need_prescription' => 0,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 1,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 15,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Levocetirizine 5mg',
                'gst_percent' => 12,
                'pack_id' => 2,
                'number_of_units' => 10,
                'unit_id' => 2,
                'category_id' => 3,
                'sub_category_id' => 3,
                'rack' => 'C2',
                'hsn_code' => '300490',
                'sch_type' => 'G',
                'manufacturer_id' => 18,
                'molecule' => 'Levocetirizine',
                'barcode' => 'LEVO5001',
                'min_threshold' => 10,
                'max_threshold' => 80,
                'need_prescription' => 0,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 1,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 12,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fexofenadine 120mg',
                'gst_percent' => 12,
                'pack_id' => 1,
                'number_of_units' => 10,
                'unit_id' => 1,
                'category_id' => 3,
                'sub_category_id' => 3,
                'rack' => 'C3',
                'hsn_code' => '300490',
                'sch_type' => 'G',
                'manufacturer_id' => 19,
                'molecule' => 'Fexofenadine',
                'barcode' => 'FEXO12001',
                'min_threshold' => 5,
                'max_threshold' => 50,
                'need_prescription' => 0,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 1,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 10,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Vitamins & Supplements (Category 4)
            [
                'name' => 'Vitamin C 500mg',
                'gst_percent' => 5,
                'pack_id' => 1,
                'number_of_units' => 30,
                'unit_id' => 1,
                'category_id' => 4,
                'sub_category_id' => 4,
                'rack' => 'D1',
                'hsn_code' => '300450',
                'sch_type' => 'G',
                'manufacturer_id' => 39,
                'molecule' => 'Ascorbic Acid',
                'barcode' => 'VITC50001',
                'min_threshold' => 5,
                'max_threshold' => 50,
                'need_prescription' => 0,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 1,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 36,
                'max_discount' => 20,
                'notes' => 'Dietary supplement',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vitamin D3 2000 IU',
                'gst_percent' => 5,
                'pack_id' => 1,
                'number_of_units' => 30,
                'unit_id' => 1,
                'category_id' => 4,
                'sub_category_id' => 4,
                'rack' => 'D2',
                'hsn_code' => '300450',
                'sch_type' => 'G',
                'manufacturer_id' => 39,
                'molecule' => 'Cholecalciferol',
                'barcode' => 'VITD20001',
                'min_threshold' => 5,
                'max_threshold' => 40,
                'need_prescription' => 0,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 0,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 36,
                'max_discount' => 15,
                'notes' => 'Bone health supplement',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vitamin B12 1000mcg',
                'gst_percent' => 5,
                'pack_id' => 1,
                'number_of_units' => 30,
                'unit_id' => 1,
                'category_id' => 4,
                'sub_category_id' => 4,
                'rack' => 'D3',
                'hsn_code' => '300450',
                'sch_type' => 'G',
                'manufacturer_id' => 40,
                'molecule' => 'Methylcobalamin',
                'barcode' => 'VITB12001',
                'min_threshold' => 5,
                'max_threshold' => 45,
                'need_prescription' => 0,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 0,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 36,
                'max_discount' => 12,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Digestive System (Category 5)
            [
                'name' => 'Omeprazole 20mg',
                'gst_percent' => 12,
                'pack_id' => 1,
                'number_of_units' => 10,
                'unit_id' => 1,
                'category_id' => 5,
                'sub_category_id' => 5,
                'rack' => 'E1',
                'hsn_code' => '300490',
                'sch_type' => 'H',
                'manufacturer_id' => 41,
                'molecule' => 'Omeprazole',
                'barcode' => 'OMEP20001',
                'min_threshold' => 5,
                'max_threshold' => 60,
                'need_prescription' => 1,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 1,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 10,
                'notes' => 'Proton pump inhibitor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Digene Gel',
                'gst_percent' => 18,
                'pack_id' => 3,
                'number_of_units' => 1,
                'unit_id' => 3,
                'category_id' => 5,
                'sub_category_id' => 5,
                'rack' => 'E2',
                'hsn_code' => '300490',
                'sch_type' => 'G',
                'manufacturer_id' => 42,
                'molecule' => 'Aluminum Hydroxide',
                'barcode' => 'DIGENE001',
                'min_threshold' => 10,
                'max_threshold' => 80,
                'need_prescription' => 0,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 0,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 8,
                'notes' => 'Antacid',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pan D',
                'gst_percent' => 12,
                'pack_id' => 1,
                'number_of_units' => 10,
                'unit_id' => 1,
                'category_id' => 5,
                'sub_category_id' => 5,
                'rack' => 'E3',
                'hsn_code' => '300490',
                'sch_type' => 'H',
                'manufacturer_id' => 41,
                'molecule' => 'Pantoprazole + Domperidone',
                'barcode' => 'PAN D001',
                'min_threshold' => 5,
                'max_threshold' => 50,
                'need_prescription' => 1,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 1,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 24,
                'max_discount' => 10,
                'notes' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Skin Care (Category 15 - using available category)
            [
                'name' => 'Betnovate Cream',
                'gst_percent' => 12,
                'pack_id' => 3,
                'number_of_units' => 1,
                'unit_id' => 3,
                'category_id' => 6,
                'sub_category_id' => 6,
                'rack' => 'F1',
                'hsn_code' => '300420',
                'sch_type' => 'H',
                'manufacturer_id' => 43,
                'molecule' => 'Betamethasone',
                'barcode' => 'BETNO001',
                'min_threshold' => 3,
                'max_threshold' => 30,
                'need_prescription' => 1,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 0,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 36,
                'max_discount' => 10,
                'notes' => 'Topical corticosteroid',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Clotrimazole Cream',
                'gst_percent' => 12,
                'pack_id' => 3,
                'number_of_units' => 1,
                'unit_id' => 3,
                'category_id' => 6,
                'sub_category_id' => 6,
                'rack' => 'F2',
                'hsn_code' => '300490',
                'sch_type' => 'G',
                'manufacturer_id' => 42,
                'molecule' => 'Clotrimazole',
                'barcode' => 'CLOTR001',
                'min_threshold' => 5,
                'max_threshold' => 40,
                'need_prescription' => 0,
                'not_for_online_sale' => 0,
                'inactive' => 0,
                'block_purchase' => 0,
                'service_item' => 0,
                'sell_loose' => 0,
                'override_loose' => 0,
                'conversion_factor' => 1,
                'unit_ratio' => 1,
                'max_self_life' => 36,
                'max_discount' => 12,
                'notes' => 'Antifungal cream',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}